name: esp_smartconfig
description: EspTouch and EspTouchV2 implementations of SmartConfig provisioning protocols. Plain Dart. All platforms.
version: 3.0.0
homepage: https://abobija.com
repository: https://github.com/abobija/esp-smartconfig-dart

environment:
  sdk: '^3.4.0'

dependencies: 
  logging: ^1.3.0
  pointycastle: ^4.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
