name: esp_smartconfig
description: Espressif's SmartConfig is a provisioning technology to connect a new Wi-Fi device to a Wi-Fi network
version: 1.0.0
homepage: https://abobija.com
repository: https://github.com/abobija/esp-smartconfig-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  test: ^1.16.0
