name: esp_smartconfig
description: EspTouch and EspTouchV2 implementations of SmartConfig provisioning protocols. Plain Dart. All platforms.
version: 2.0.4
homepage: https://abobija.com
repository: https://github.com/abobija/esp-smartconfig-dart

environment:
  sdk: '^3.4.0'

dependencies: 
  logging: ^1.3.0
  pointycastle: ^3.9.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.26.2
