name: esp_smartconfig
description: Espressif's SmartConfig provisioning protocols written in plain Dart. No platform specific.
version: 1.0.0
homepage: https://abobija.com
repository: https://github.com/abobija/esp-smartconfig-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  loggerx: ^1.3.3

dev_dependencies:
  test: ^1.16.0
