name: esp_smartconfig
description: EspTouch and EspTouchV2 implementations of SmartConfig provisioning protocols. Plain Dart. All platforms.
version: 1.1.10
homepage: https://abobija.com
repository: https://github.com/abobija/esp-smartconfig-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  loggerx: ^1.3.4
  pointycastle: ^3.1.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
