name: esp_smartconfig
description: EspTouch and EspTouchV2 implementations of SmartConfig provisioning protocols. Plain Dart. All platforms.
version: 2.0.2
homepage: https://abobija.com
repository: https://github.com/abobija/esp-smartconfig-dart

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  loggerx: ^2.0.0
  pointycastle: ^3.7.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
